### ISSUE TITLE
Cluster stop working after killing leader manually

### ISSUE THREAD

**Issue by wanghaofeng03** [atomix/atomix#1065]
I am playing around with Atomix cluster. Basically I would like to configure a DistributedMap for data sharing within several nodes.
The cluster is configured with a system management group based on raft protocol and a partition group based on primary-backup protocol. After that, I create a DistributedMap for data storing. I have a thread writing data and another thread reading data every three seconds to test the availability and functionality of the map and members.
Everything goes right after starting. However, when I try to kill partition group leader manually, there's a high probability that remaining members throw Timeout Exception when accessing map and can not resume working.

**test code**

```java
    public static void main(String[] args) {
        AtomixBuilder builder = Atomix.builder();

        String strDatapath = "data1";
        File fDatapath = new File(strDatapath);

        builder.withMemberId("m1")
                .withHost("127.0.0.1")
                .withPort(5679)
                .withMembershipProvider(BootstrapDiscoveryProvider.builder()
                        .withNodes(
                                Node.builder().withId("m1").withHost("127.0.0.1").withPort(5679).build(),
                                Node.builder().withId("m2").withHost("127.0.0.1").withPort(5680).build(),
                                Node.builder().withId("m3").withHost("127.0.0.1").withPort(5681).build(),
                                Node.builder().withId("m4").withHost("127.0.0.1").withPort(5682).build(),
                                Node.builder().withId("m5").withHost("127.0.0.1").withPort(5683).build())
                        .build())
                .withManagementGroup(RaftPartitionGroup.builder("system")
                        .withDataDirectory(fDatapath)
                        .withPartitionSize(5)
                        .withNumPartitions(1)
                        .withMembers("m1","m2","m3","m4","m5")
                        .build())
                .withPartitionGroups(
                        PrimaryBackupPartitionGroup.builder("data")
                                .withNumPartitions(1)
                                .build()
                )
                .build();

        Atomix atomix = builder.build();

        atomix.start().join();

        MultiPrimaryProtocol protocol = MultiPrimaryProtocol.builder()
                .withMaxRetries(3)
                .withConsistency(Consistency.EVENTUAL)
                .withBackups(1)
                .build();

        DistributedMapBuilder<String, Long> mapBuilder = atomix.<String, Long>mapBuilder("my-distributed-map")
                .withProtocol(protocol)
                .withKeyType(String.class)
                .withValueType(Long.class);
        DistributedMap<String, Long> map = mapBuilder.build();

        // new thread for writing
        new Thread(() -> {
            while (true) {
                try {
                    // sleep for 3 seconds
                    Thread.sleep(3000);
                    map.put("M1", System.currentTimeMillis());

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();

        // another thread for reading
        new Thread(() -> {
            while (true) {
                try {
                    Thread.sleep(3000);
                    map.entrySet().forEach(System.out::println);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();

        // map.close();
    }

```
** output **
```java
io.atomix.primitive.PrimitiveException$Timeout
	at io.atomix.core.iterator.impl.BlockingIterator.complete(BlockingIterator.java:66)
	at io.atomix.core.iterator.impl.BlockingIterator.hasNext(BlockingIterator.java:41)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at distributed.map.protobuftest.Member1.lambda$main$3(Member1.java:178)
	at java.base/java.lang.Thread.run(Thread.java:830)
io.atomix.primitive.PrimitiveException$Timeout
	at io.atomix.core.map.impl.BlockingDistributedMap.complete(BlockingDistributedMap.java:195)
	at io.atomix.core.map.impl.BlockingDistributedMap.put(BlockingDistributedMap.java:81)
	at distributed.map.protobuftest.Member1.lambda$main$2(Member1.java:150)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

Member1.java:150 is the line I put data into map and Member1.java:178 is the line I try to print entrySet from the map.

Is this a bug or anything wrong in my usage? 

**Environment**

Atomix: 3.1.5
Atomix Vertx: 1.0.0-SNAPSHOT
OS: macOS
JVM: 13.0.2

**Comment by wanghaofeng03** [comment]
@kuujo @jhalterman  @johnou Can anybody help me ?

**Comment by ssteiner** [comment]
I'm having the same issue.. I only have two nodes, using simple ``Profile.dataGrid()`` and I'm creating the map as follows

```
        DistributedMapBuilder<String, String> mapBuilder = atomix.mapBuilder(mapName);
        map = mapBuilder.withCacheEnabled().build();
```

it all works fine until I kill the first started app (which I presume is the leader). If I instead stop the second instance, I can still write to /read from the map, so it's really only happening when killing the leader.

**Comment by ddcprg** [comment]
I have the same issue apparently
