### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer on Atomix::start

### ISSUE THREAD

**Issue by franz1981** [atomix/atomix#1066]
**Expected behavior**

The Atomix instance should start correctly

**Actual behavior**

Fail with:
```java
java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
        at io.atomix.storage.journal.JournalSegmentDescriptor$Builder.build(JournalSegmentDescriptor.java:285)
        at io.atomix.storage.journal.SegmentedJournal.open(SegmentedJournal.java:250)
        at io.atomix.storage.journal.SegmentedJournal.<init>(SegmentedJournal.java:97)
        at io.atomix.storage.journal.SegmentedJournal$Builder.build(SegmentedJournal.java:873)
        at io.atomix.protocols.raft.storage.log.RaftLog$Builder.build(RaftLog.java:309)
        at io.atomix.protocols.raft.storage.RaftStorage.openLog(RaftStorage.java:336)
        at io.atomix.protocols.raft.impl.RaftContext.<init>(RaftContext.java:163)
        at io.atomix.protocols.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:267)
        at io.atomix.protocols.raft.impl.DefaultRaftServer$Builder.build(DefaultRaftServer.java:228)
        at io.atomix.protocols.raft.partition.impl.RaftPartitionServer.buildServer(RaftPartitionServer.java:180)
        at io.atomix.protocols.raft.partition.impl.RaftPartitionServer.start(RaftPartitionServer.java:92)
        at io.atomix.protocols.raft.partition.RaftPartition.open(RaftPartition.java:136)
        at io.atomix.protocols.raft.partition.RaftPartitionGroup.lambda$join$6(RaftPartitionGroup.java:241)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at io.atomix.protocols.raft.partition.RaftPartitionGroup.join(RaftPartitionGroup.java:243)
        at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$1(DefaultPartitionService.java:158)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
        at io.atomix.primitive.partition.impl.DefaultPartitionService.lambda$start$2(DefaultPartitionService.java:150)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:995)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
        at io.atomix.primitive.partition.impl.DefaultPartitionService.start(DefaultPartitionService.java:138)
        at io.atomix.core.Atomix.lambda$startServices$3(Atomix.java:853)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
        at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
Due to https://github.com/eclipse/jetty.project/issues/3244#issue-396988904

```

**Environment**

 - Atomix: 3.1.7
 - OS: Linux matrix 4.18.16-300.fc29.x86_64 #1 SMP Sat Oct 20 23:24:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - JVM OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

**Comment by johnou** [comment]
https://github.com/atomix/atomix/pull/1064

**Comment by franz1981** [comment]
@johnou Happy to see you :)

**Comment by johnou** [comment]
@franz1981 likewise!

**Comment by franz1981** [comment]
Many thanks!!!!
