### ISSUE TITLE
Calling close on single replica cluster throws NullPointerException

### ISSUE THREAD

**Issue by joachimdb** [atomix/atomix#154]
Creating a replica on a single node only and closing it again throws a NullPointerException. It's impossible to then close the replica or the underlying transport.

In clojure:

```
  (def t (NettyTransport.))
  (def r (-> (AtomixReplica/builder (Address. "localhost" 8011) [(Address. "localhost" 8011)])
             (.withTransport t)
             (.withStorage (Storage.))
             (.build)))
  (def o (.open r))
```

This produces the following log entries:
```
2016-03-10 15:39:07.472 [copycat-server-localhost/127.0.0.1:8011] INFO  i.a.catalyst.transport.NettyServer - Binding to localhost/127.0.0.1:8011
2016-03-10 15:39:07.563 [copycat-server-localhost/127.0.0.1:8011] INFO  i.a.catalyst.transport.NettyServer - Listening at /127.0.0.1:8011
2016-03-10 15:39:07.573 [copycat-server-localhost/127.0.0.1:8011] INFO  i.a.catalyst.transport.NettyClient - Connecting to Joachims-Air/192.168.1.35:8011
2016-03-10 15:39:09.119 [copycat-server-localhost/127.0.0.1:8011] INFO  i.a.catalyst.transport.NettyClient - Connecting to Joachims-Air/192.168.1.35:8011
...
```

Now when closing the replica, even after canceling the open request, throws a NullPointerException:
```
  (.isDone o) ;; => false
  (.cancel o true) ;; => true
  (.close r)
```
=>
```
1. Unhandled java.lang.NullPointerException
   (No message)

            AtomixReplica.java:  255  io.atomix.AtomixReplica/close
 NativeMethodAccessorImpl.java:   -2  sun.reflect.NativeMethodAccessorImpl/invoke0
 NativeMethodAccessorImpl.java:   62  sun.reflect.NativeMethodAccessorImpl/invoke
DelegatingMethodAccessorImpl.java:   43  sun.reflect.DelegatingMethodAccessorImpl/invoke
                   Method.java:  483  java.lang.reflect.Method/invoke
                Reflector.java:   93  clojure.lang.Reflector/invokeMatchingMethod
                Reflector.java:  313  clojure.lang.Reflector/invokeNoArgInstanceMember
                          REPL:    1  eais.atomix/eval14487
                 Compiler.java: 6782  clojure.lang.Compiler/eval
                 Compiler.java: 6745  clojure.lang.Compiler/eval
                      core.clj: 3081  clojure.core/eval
                      main.clj:  240  clojure.main/repl/read-eval-print/fn
                      main.clj:  240  clojure.main/repl/read-eval-print
                      main.clj:  258  clojure.main/repl/fn
                      main.clj:  258  clojure.main/repl
                   RestFn.java: 1523  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   58  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                      AFn.java:  152  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  630  clojure.core/apply
                      core.clj: 1868  clojure.core/with-bindings*
                   RestFn.java:  425  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   56  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  191  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
        interruptible_eval.clj:  159  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                      AFn.java:   22  clojure.lang.AFn/run
       ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run

```

Furthermore, the Transport keeps attempting to connect ...

If the transport is closed this is logged repeatedly:

```
2016-03-10 15:44:52.008 [copycat-server-localhost/127.0.0.1:8011] WARN  io.netty.channel.AbstractChannel - Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x57753938]
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:735) ~[netty-common-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:312) ~[netty-common-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:718) ~[netty-common-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:416) ~[netty-transport-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:48) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:306) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:133) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:115) [netty-transport-4.0.21.Final.jar:4.0.21.Final]
	at io.atomix.catalyst.transport.NettyClient.connect(NettyClient.java:93) [catalyst-netty-1.0.1.jar:na]
	at io.atomix.copycat.server.state.ConnectionManager.createConnection(ConnectionManager.java:69) [copycat-server-1.0.0-rc2.jar:na]
	at io.atomix.copycat.server.state.ConnectionManager.getConnection(ConnectionManager.java:47) [copycat-server-1.0.0-rc2.jar:na]
	at io.atomix.copycat.server.state.ClusterState.join(ClusterState.java:358) [copycat-server-1.0.0-rc2.jar:na]
	at io.atomix.copycat.server.state.ClusterState.lambda$resetJoinTimer$55(ClusterState.java:457) [copycat-server-1.0.0-rc2.jar:na]
	at io.atomix.copycat.server.state.ClusterState$$Lambda$49/698747052.run(Unknown Source) [copycat-server-1.0.0-rc2.jar:na]
	at io.atomix.catalyst.util.concurrent.Runnables.lambda$logFailure$17(Runnables.java:20) [catalyst-common-1.0.1.jar:na]
	at io.atomix.catalyst.util.concurrent.Runnables$$Lambda$9/1378966379.run(Unknown Source) [catalyst-common-1.0.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_05]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_05]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_05]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
```

The only way to stop in the end is killing the JVM...

**Comment by kuujo** [comment]
@joachimdb this is because the replica is being closed before it was ever opened, so the internal state was never populated (specifically the lock). However, this is using the last RC and a lot has changed since then. The variable on which the NPE is thrown no longer exists in `master`, so this shouldn't be an issue.
