### ISSUE TITLE
Using BalancingClusterManager causes null pointer exception

### ISSUE THREAD

**Issue by hrosenbe** [atomix/atomix#192]
Any use of the BalancingClusterManager causes a null pointer exception when bootstrapping a cluster.

This is easily replicated by editing LeaderElectionExample.java to add the use of the BalancingClusterManager:

```
 // Create a stateful Atomix replica. The replica communicates with other replicas in the cluster
 // to replicate state changes.
 AtomixReplica atomix = AtomixReplica.builder(address)
```
-       .withClusterManager(BalancingClusterManager.builder()
-                           .withQuorumHint(3)
-                           .withBackupCount(1)
-                           .build())
     .withTransport(new NettyTransport())
     .withStorage(new Storage(args[0]))
     .build();

The example still builds correctly, but running it yields:

Exception in thread "main" java.util.concurrent.CompletionException: java.lang.NullPointerException
    at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
    at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
    at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
    at io.atomix.copycat.server.CopycatServer.lambda$null$28(CopycatServer.java:655)
    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
    at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
    at io.atomix.copycat.server.state.ClusterState.identify(ClusterState.java:432)
    at io.atomix.copycat.server.state.ServerContext.setLeader(ServerContext.java:261)
    at io.atomix.copycat.server.state.LeaderState.takeLeadership(LeaderState.java:80)
    at io.atomix.copycat.server.state.LeaderState.open(LeaderState.java:63)
    at io.atomix.copycat.server.state.ServerContext.transition(ServerContext.java:608)
    at io.atomix.copycat.server.state.CandidateState.lambda$sendVoteRequests$142(CandidateState.java:117)
    at io.atomix.copycat.server.util.Quorum.checkComplete(Quorum.java:42)
    at io.atomix.copycat.server.util.Quorum.succeed(Quorum.java:55)
    at io.atomix.copycat.server.state.CandidateState.lambda$null$143(CandidateState.java:170)
    at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
    at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
    at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
    at io.atomix.catalyst.concurrent.Runnables.lambda$logFailure$2(Runnables.java:20)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
    ... 28 more

The source of the problem has been previously identified (on gitter): https://gitter.im/atomix/atomix?at=5720ffda4da16e7d13d95c4c

I am using the artifacts from Maven Central (currently using rc8), and would rather not make the change and build myself.  Will the fix for this make it into a release any time soon?  I am looking at a scenario where replicas may come and go fairly frequently as an application scales up and down, and would rather not try to roll my own cluster management logic.

**Comment by hrosenbe** [comment]
Any chance that this will be fixed in an upcoming release?

**Comment by ccleve** [comment]
I'm seeing the same behavior. My workaround is to bootup three machines using AtomixReplica and the rest using AtomixClient.

**Comment by kuujo** [comment]
I'll take a look at it tonight. Happy to release a fix in a minor release as soon as it's committed.

**Comment by dorzepowski** [comment]
Same issue for me, Any chance that this will be fixed soon in minor release?

**Comment by TSavo** [comment]
Are we still waiting on the merge of this PR?

**Comment by johnou** [comment]
Yes, https://github.com/atomix/atomix/pull/283 is still open.
