### ISSUE TITLE
Cannot start standalone jar

### ISSUE THREAD

**Issue by theminecoder** [atomix/atomix#193]
Tried launching the stand alone jar on my windows local development machine with the example config from the repo and this showed up:

```
Exception in thread "main" io.atomix.catalyst.serializer.RegistrationException: no default serializer found for type: class io.atomix.copycat.protocol.UnregisterRequest
        at io.atomix.catalyst.serializer.SerializerRegistry.register(SerializerRegistry.java:122)
        at io.atomix.copycat.protocol.ClientRequestTypeResolver.resolve(ClientRequestTypeResolver.java:44)
        at io.atomix.catalyst.serializer.SerializerRegistry.resolve(SerializerRegistry.java:78)
        at io.atomix.catalyst.serializer.SerializerRegistry.resolve(SerializerRegistry.java:62)
        at io.atomix.catalyst.serializer.Serializer.resolve(Serializer.java:301)
        at io.atomix.copycat.server.CopycatServer$Builder.build(CopycatServer.java:1040)
        at io.atomix.manager.ResourceServer$Builder.build(ResourceServer.java:624)
        at io.atomix.standalone.server.StandaloneServer.main(StandaloneServer.java:67)
```

Jar version: `atomix-standalone-server-1.0.0-rc4-shaded.jar`

**Comment by theminecoder** [comment]
Never mind, realized it was an older version.
