### ISSUE TITLE
StackOverflowError with leader state messaging

### ISSUE THREAD

**Issue by johnou** [atomix/atomix#205]
```java
2016-11-19T00:51:27,800 ERROR [copycat-server-localhost/127.0.0.1:8700-copycat] (io.atomix.catalyst.concurrent.SingleThreadContext) An uncaught exception occurred []
java.lang.StackOverflowError: null
	at io.atomix.catalyst.serializer.Serializer.writeObject(Serializer.java:860) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.resource.internal.ResourceOperation.writeObject(ResourceOperation.java:52) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.resource.internal.ResourceCommand.writeObject(ResourceCommand.java:45) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.catalyst.serializer.util.CatalystSerializableSerializer.write(CatalystSerializableSerializer.java:51) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.catalyst.serializer.util.CatalystSerializableSerializer.write(CatalystSerializableSerializer.java:45) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.catalyst.serializer.Serializer.writeById(Serializer.java:896) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.catalyst.serializer.Serializer.writeObject(Serializer.java:885) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.manager.resource.internal.InstanceOperation.writeObject(InstanceOperation.java:67) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.catalyst.serializer.util.CatalystSerializableSerializer.write(CatalystSerializableSerializer.java:51) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.catalyst.serializer.util.CatalystSerializableSerializer.write(CatalystSerializableSerializer.java:45) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.catalyst.serializer.Serializer.writeById(Serializer.java:896) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.catalyst.serializer.Serializer.writeObject(Serializer.java:885) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.storage.entry.CommandEntry.writeObject(CommandEntry.java:79) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.catalyst.serializer.util.CatalystSerializableSerializer.write(CatalystSerializableSerializer.java:51) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.catalyst.serializer.util.CatalystSerializableSerializer.write(CatalystSerializableSerializer.java:45) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.catalyst.serializer.Serializer.writeById(Serializer.java:896) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.catalyst.serializer.Serializer.writeObject(Serializer.java:885) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.catalyst.serializer.Serializer.writeObject(Serializer.java:820) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.storage.Segment.append(Segment.java:311) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.storage.Log.append(Log.java:294) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:516) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.applyCommand(LeaderState.java:524) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.LeaderState.lambda$sequenceCommand$169(LeaderState.java:493) ~[atomix-all-1.0.0-rc9.jar:?]
	at io.atomix.copycat.server.state.ServerSessionContext.setRequestSequence(ServerSessionContext.java:267) ~[atomix-all-1.0.0-rc9.jar:?]
```

**Comment by johnou** [comment]
Run Main a couple of times to reproduce.

[atomix-proto.zip](https://github.com/atomix/atomix/files/601119/atomix-proto.zip)

**Comment by kuujo** [comment]
atomix/copycat#267
