### ISSUE TITLE
Adding nodes to cluster in parallel sometimes fails

### ISSUE THREAD

**Issue by pawel-kaminski-krk** [atomix/atomix#397]
hi,
I am playing with adding/removing nodes to cluster. I get strange behavior when running code  https://gist.github.com/pawel-kaminski-krk/d351c6f9450bce8421bfc47221da6307  

sometimes it runs OK, but sometimes it fails to make a progress. It only happens when nodes are added in parallel.

```
07:22:42.454 [main] INFO  MDC[] io.carousel.it.AddNewNodes - server4/5 joining cluster
07:22:42.455 [main] WARN  MDC[] io.atomix.messaging.impl.NettyMessagingService - Disabling TLS for intra-cluster messaging; Could not load cluster key store: ../config/atomix.jks (No such file or directory)
07:22:42.458 [main] WARN  MDC[] io.atomix.messaging.impl.NettyMessagingService - Disabling TLS for intra-cluster messaging; Could not load cluster key store: ../config/atomix.jks (No such file or directory)
07:22:42.526 [raft-server-core-partition-1] WARN  MDC[] io.atomix.protocols.raft.impl.DefaultRaftServer - RaftServer{core-partition-1} - Failed to start server!
07:22:45.185 [raft-server-coordination-partition-4] WARN  MDC[] io.atomix.protocols.raft.roles.FollowerRole - RaftServer{coordination-partition-4}{role=FOLLOWER} - io.atomix.messaging.MessagingException$NoRemoteHandler: No remote message handler registered for this message
07:22:47.365 [raft-server-core-partition-1] WARN  MDC[] io.atomix.protocols.raft.roles.FollowerRole - RaftServer{core-partition-1}{role=FOLLOWER} - Unknown nodeId: server5
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.IllegalStateException: not a member of the cluster
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:769)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.atomix.protocols.raft.cluster.impl.RaftClusterContext.lambda$join$10(RaftClusterContext.java:413)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: not a member of the cluster
	... 11 more
07:22:47.648 [ForkJoinPool.commonPool-worker-5] INFO  MDC[] io.carousel.it.AddNewNodes - completed adding 4 and 5
 java.util.concurrent.CompletionException: java.lang.IllegalStateException: not a member of the cluster
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_92]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_92]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:769) ~[?:1.8.0_92]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_92]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_92]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_92]
	at io.atomix.protocols.raft.cluster.impl.RaftClusterContext.lambda$join$10(RaftClusterContext.java:413) ~[atomix-raft-2.1.0-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_92]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_92]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_92]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_92]
Caused by: java.lang.IllegalStateException: not a member of the cluster
```

**Comment by johnou** [comment]
When running this test I was sometimes running into https://github.com/atomix/atomix/issues/366 unfortunately after applying the fix there are still issues.

**Comment by johnou** [comment]
With the phi fix applied I now see the following errors when trying to join a cluster..

```java
public class Bootstrap {

    private static final Logger logger = LogManager.getLogger(Bootstrap.class);

    private static final Object lock = new Object();

    public static void main(String[] args) throws InterruptedException {
        Node[] bootstrapNodes = new Node[] {Node.builder("server1")
                .withType(Node.Type.DATA)
                .withEndpoint(Endpoint.from("127.0.0.1", 5001))
                .build(),
                Node.builder("server2")
                        .withType(Node.Type.DATA)
                        .withEndpoint(Endpoint.from("127.0.0.1", 5002))
                        .build() };

        Atomix atomix1 = createAtomicNode("server1", 5001, bootstrapNodes);
        Atomix atomix2 = createAtomicNode("server2", 5002, bootstrapNodes);

        CompletableFuture.allOf(atomix1.start(), atomix2.start()).whenCompleteAsync((aVoid, throwable) -> {

        }).join();


        Atomix atomix3 = createAtomicNode("server3", 5003, bootstrapNodes);
        Atomix atomix4 = createAtomicNode("server4", 5004, bootstrapNodes);

        CompletableFuture.allOf(atomix3.start(), atomix4.start()).whenCompleteAsync((aVoid, throwable) -> {

        }).join();

        for (Node node : atomix1.clusterService().getNodes()) {
            logger.info("node {} is in state {}.", node, node.getState());
        }

        CompletableFuture.allOf(atomix3.stop(), atomix4.stop()).whenCompleteAsync((aVoid, throwable) -> {

        }).join();

        for (Node node : atomix1.clusterService().getNodes()) {
            logger.info("node {} is in state {}.", node, node.getState());
        }

        logger.info("done");

        synchronized (lock) {
            lock.wait();
        }
    }

    private static Atomix createAtomicNode(String nodeId, int port, Node[] bootstrapNodes) {
        Atomix.Builder builder = Atomix.builder();
        builder.withLocalNode(Node.builder(nodeId)
                .withType(Node.Type.DATA)
                .withEndpoint(Endpoint.from("127.0.0.1", port))
                .build());

        return builder.withDataDirectory(new File(System.getProperty("user.dir"), "data/" + nodeId)).withBootstrapNodes(bootstrapNodes).build();
    }
}
```

```
2018-01-16T12:20:41,678 ERROR [raft-client-core-partition-1-1] (io.atomix.utils.concurrent.ThreadPoolContext) An uncaught exception occurred []
java.lang.IllegalArgumentException: Unknown nodeId: server3
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:203) ~[guava-22.0.jar:?]
	at io.atomix.cluster.messaging.impl.DefaultClusterMessagingService.doUnicast(DefaultClusterMessagingService.java:136) ~[atomix-cluster-2.1.0-sulake.jar:?]
	at io.atomix.cluster.messaging.impl.DefaultClusterMessagingService.lambda$multicast$1(DefaultClusterMessagingService.java:113) ~[atomix-cluster-2.1.0-sulake.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_131]
	at io.atomix.cluster.messaging.impl.DefaultClusterMessagingService.multicast(DefaultClusterMessagingService.java:113) ~[atomix-cluster-2.1.0-sulake.jar:?]
	at io.atomix.protocols.raft.partition.impl.RaftClientCommunicator.reset(RaftClientCommunicator.java:111) ~[atomix-raft-2.1.0-sulake.jar:?]
	at io.atomix.protocols.raft.proxy.impl.RaftProxyListener.handlePublish(RaftProxyListener.java:114) ~[atomix-raft-2.1.0-sulake.jar:?]
	at io.atomix.cluster.messaging.impl.DefaultClusterMessagingService$InternalMessageConsumer.accept(DefaultClusterMessagingService.java:243) ~[atomix-cluster-2.1.0-sulake.jar:?]
	at io.atomix.cluster.messaging.impl.DefaultClusterMessagingService$InternalMessageConsumer.accept(DefaultClusterMessagingService.java:232) ~[atomix-cluster-2.1.0-sulake.jar:?]
	at io.atomix.messaging.impl.NettyMessagingService.lambda$null$17(NettyMessagingService.java:485) ~[atomix-messaging-2.1.0-sulake.jar:?]
	at io.atomix.utils.concurrent.ThreadPoolContext.lambda$new$0(ThreadPoolContext.java:81) ~[atomix-utils-2.1.0-sulake.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

upon restarting the application without clearing the data dir the bootstrap nodes fail to form a cluster..

```
2018-01-16T12:26:55,050 INFO  [atomix-0] (io.atomix.cluster.messaging.impl.DefaultClusterEventingService) Started []
2018-01-16T12:26:55,050 INFO  [atomix-0] (io.atomix.cluster.messaging.impl.DefaultClusterEventingService) Started []
2018-01-16T12:26:55,126 INFO  [atomix-0] (io.atomix.protocols.raft.partition.impl.RaftPartitionServer) Starting server for partition PartitionId{id=1, group=core} []
2018-01-16T12:26:55,126 INFO  [atomix-0] (io.atomix.protocols.raft.partition.impl.RaftPartitionServer) Starting server for partition PartitionId{id=1, group=core} []
2018-01-16T12:26:55,275 INFO  [raft-server-core-partition-1] (io.atomix.protocols.raft.impl.RaftContext) RaftServer{core-partition-1} - Transitioning to FOLLOWER []
2018-01-16T12:26:55,277 INFO  [raft-server-core-partition-1] (io.atomix.protocols.raft.impl.RaftContext) RaftServer{core-partition-1} - Transitioning to FOLLOWER []
2018-01-16T12:26:58,629 WARN  [raft-server-core-partition-1] (io.atomix.protocols.raft.roles.FollowerRole) RaftServer{core-partition-1}{role=FOLLOWER} - Unknown nodeId: server4 []
2018-01-16T12:26:58,630 WARN  [raft-server-core-partition-1] (io.atomix.protocols.raft.roles.FollowerRole) RaftServer{core-partition-1}{role=FOLLOWER} - Unknown nodeId: server3 []
2018-01-16T12:26:59,103 WARN  [raft-server-core-partition-1] (io.atomix.protocols.raft.roles.FollowerRole) RaftServer{core-partition-1}{role=FOLLOWER} - Unknown nodeId: server4 []
2018-01-16T12:26:59,103 WARN  [raft-server-core-partition-1] (io.atomix.protocols.raft.roles.FollowerRole) RaftServer{core-partition-1}{role=FOLLOWER} - Unknown nodeId: server3 []
2018-01-16T12:27:03,866 WARN  [raft-server-core-partition-1] (io.atomix.protocols.raft.roles.FollowerRole) RaftServer{core-partition-1}{role=FOLLOWER} - Unknown nodeId: server4 []
2018-01-16T12:27:03,867 WARN  [raft-server-core-partition-1] (io.atomix.protocols.raft.roles.FollowerRole) RaftServer{core-partition-1}{role=FOLLOWER} - Unknown nodeId: server3 []
2018-01-16T12:27:05,761 WARN  [raft-server-core-partition-1] (io.atomix.protocols.raft.roles.FollowerRole) RaftServer{core-partition-1}{role=FOLLOWER} - Unknown nodeId: server4 []
2018-01-16T12:27:05,761 WARN  [raft-server-core-partition-1] (io.atomix.protocols.raft.roles.FollowerRole) RaftServer{core-partition-1}{role=FOLLOWER} - Unknown nodeId: server3 []
2018-01-16T12:27:08,919 WARN  [raft-server-core-partition-1] (io.atomix.protocols.raft.roles.FollowerRole) RaftServer{core-partition-1}{role=FOLLOWER} - Unknown nodeId: server4 []
2018-01-16T12:27:08,919 WARN  [raft-server-core-partition-1] (io.atomix.protocols.raft.roles.FollowerRole) RaftServer{core-partition-1}{role=FOLLOWER} - Unknown nodeId: server3 []
2018-01-16T12:27:11,339 WARN  [raft-server-core-partition-1] (io.atomix.protocols.raft.roles.FollowerRole) RaftServer{core-partition-1}{role=FOLLOWER} - Unknown nodeId: server4 []
2018-01-16T12:27:11,339 WARN  [raft-server-core-partition-1] (io.atomix.protocols.raft.roles.FollowerRole) RaftServer{core-partition-1}{role=FOLLOWER} - Unknown nodeId: server3 []
```

**Comment by johnou** [comment]
@pawel-kaminski-krk would you please try again with 2.1.0-beta2?

**Comment by pawel-kaminski-krk** [comment]
im working on snapshot, and I think it is fixed now

**Comment by johnou** [comment]
2.1.0-beta2 should have all the fixes, when you get a moment please give it a go and if it looks good kindly close the issue.

**Comment by pawel-kaminski-krk** [comment]
Ok.

**Comment by johnou** [comment]
@kuujo should be good to close.
