### ISSUE TITLE
Observed ConcurrentModificationException in DefaultServiceExecutor

### ISSUE THREAD

**Issue by johnou** [atomix/atomix#526]
```
19:27:20.586 [raft-server-system-partition-1-state] WARN i.a.protocols.raft.roles.LeaderRole - RaftServer{system-partition-1}{role=LEADER} - An unexpected error occurred: {}
java.util.ConcurrentModificationException: null
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[na:1.8.0_131]
at java.util.ArrayList$Itr.remove(ArrayList.java:865) ~[na:1.8.0_131]
at io.atomix.primitive.service.impl.DefaultServiceExecutor.tick(DefaultServiceExecutor.java:108) ~[classes/:na]
at io.atomix.primitive.service.AbstractPrimitiveService.tick(AbstractPrimitiveService.java:75) ~[classes/:na]
at io.atomix.protocols.raft.service.RaftServiceContext.tick(RaftServiceContext.java:183) ~[classes/:na]
at io.atomix.protocols.raft.service.RaftServiceContext.executeCommand(RaftServiceContext.java:426) ~[classes/:na]
at io.atomix.protocols.raft.impl.RaftServiceManager.applyCommand(RaftServiceManager.java:740) ~[classes/:na]
at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$apply$12(RaftServiceManager.java:397) ~[classes/:na]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_131]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_131]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_131]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
```

**Comment by johnou** [comment]
@kuujo looks like cancel was invoked while ticking?

**Comment by kuujo** [comment]
I haven't found how this could be possible. State machine methods are always called from that single thread.

**Comment by kuujo** [comment]
Actually this may be a bug that has since been fixed.

**Comment by johnou** [comment]
Let's close it for now then.
