### ISSUE TITLE
AtomixAgent argument 'bootstrap' return NodeConfig List, but BootstrapDiscoveryConfig need Node List

### ISSUE THREAD

**Issue by aruanruan** [atomix/atomix#699]
AtomixAgent.java
line 48:  return NodeConfig
line127: convert to List<node>

when i use  shell:
ava -jar  -c atomix.conf --bootstrap member1@localhost:5001 member2@localhost:5002 member3@localhost:5003 --http-port 8081 

Exception in thread "main" java.util.concurrent.CompletionException: java.lang.ClassCastException: io.atomix.cluster.NodeConfig cannot be cast to io.atomix.cluster.Node
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by johnou** [comment]
Should be fixed with https://github.com/atomix/atomix/pull/705
