### ISSUE TITLE
memory mapped segment  compacting  throw exception when closeing MappedBytes & deleting file

### ISSUE THREAD

**Issue by aruanruan** [atomix/atomix#722]
java.lang.RuntimeException: java.nio.file.FileSystemException: target\perf-logs\1\atomix-1.log: The process cannot access the file because it is being used by another process
        at io.atomix.storage.buffer.MappedBytes.delete(MappedBytes.java:xxx) ~[classes/:na]
	at io.atomix.storage.buffer.MappedBuffer.delete(MappedBuffer.java:xxx) ~[classes/:na]
	at io.atomix.storage.journal.JournalSegmentWriter.delete(JournalSegmentWriter.java:263) ~[classes/:na]
	at io.atomix.storage.journal.JournalSegment.delete(JournalSegment.java:190) ~[classes/:na]
	at io.atomix.storage.journal.SegmentedJournal.compact(SegmentedJournal.java:643) ~[classes/:na]
	at io.atomix.protocols.raft.storage.log.RaftLog.compact(RaftLog.java:128) ~[classes/:na]
	at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$7(RaftServiceManager.java:291) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:1.8.0_144]

THIS is a very old BUG: 

https://bugs.java.com/view_bug.do?bug_id=4829325

 
I tried some solutions : 
https://qiita.com/ajis_ka/items/e89cd2472e961bac69bc
https://github.com/apache/lucene-solr/blob/master/lucene/core/src/java/org/apache/lucene/store/MMapDirectory.java#L339

but it does not WORK yet

**Environment**

 - Atomix: 3.0.0
 - OS:  windows 10
 - JVM 1.8.0-131

<sup>:warning:️ Please verify that your issue still occurs on the latest version of Atomix before reporting. 
The documentation is currently work-in-progress and is not yet complete.</sup>

-----------------------------------------------------------------------------------------
*Have you searched the CLOSED issues already? How about checking in with the Atomix [google group](https://groups.google.com/forum/#!forum/atomixio)?*

**Comment by johnou** [comment]
We free the direct buffer here https://github.com/atomix/atomix/blob/b48608543581dbc1ba56f568efa199c377a993a3/utils/src/main/java/io/atomix/utils/memory/MappedMemory.java#L80

**Comment by johnou** [comment]
@aruanruan can you see if this fixes the problem? https://github.com/atomix/atomix/pull/728

**Comment by johnou** [comment]
@aruanruan ping
