### ISSUE TITLE
NullPointerExceptions and frozen client

### ISSUE THREAD

**Issue by zwillim** [atomix/atomix#746]
**I tried to send messages to leader, but failed.**

I start a server with `Profile.dataGrid()` and ran a `LeaderElection`. Then I started 5 client threads to send a lot of messages to leader. I tried for several times. Sometimes the client freeze when join the cluster, sometimes the client got nothing from the leader election, and sometimes the client freeze during sending msgs.

My server is like this:
```java

        final String server = "server1";
        final int port = 5001;
        AtomixBuilder builder = Atomix.builder();
        builder.withAddress("127.0.0.1", port).withMembershipProvider(new BootstrapDiscoveryProvider(Node.builder().withAddress("127.0.0.1:5001").build())).addProfile(Profile.dataGrid());
        Atomix atomix = builder.build();
        AtomicInteger i = new AtomicInteger();
        atomix.getMessagingService().registerHandler("test_type", (Address addr, byte[] bs) -> {
            System.out.println("coming in test_type, addr:" + addr + ", cmd:" + new String(bs));
            return CompletableFuture.completedFuture(("return_" + i.getAndIncrement() + "_" + new String(bs) + "_from_" + server).getBytes());
        });
        atomix.getMembershipService().addListener(event -> System.out.println(event.toString()));
        System.out.println("trying to start " + server + " on port " + port + ".");
        atomix.start().join();
        System.out.println(server + " started on port " + port + ".");

        LeaderElection<MemberId> election = atomix.<MemberId>leaderElectionBuilder("group").withSerializer(Serializer.using(Namespace.builder()
                .register(Namespaces.BASIC)
                .nextId(Namespaces.BEGIN_USER_CUSTOM_ID)
                .register(MemberId.class)
                .build())).build();

        election.addListener((event) -> {
            if (event.newLeadership().leader().id().equals(atomix.getMembershipService().getLocalMember().id())) {
                System.out.println("I'm the leader, member id: " + event.newLeadership().leader().id() + ",old:" + event.oldLeadership().leader().id() + ",topic:" + event.topic() + ",term" + event.newLeadership().leader().term());
            } else {
                System.out.println("I'm not leader, member id: " + event.newLeadership().leader().id() + ",old:" + event.oldLeadership().leader().id() + ",topic:" + event.topic() + ",term" + event.newLeadership().leader().term());
            }
        });
        Leadership leadership = election.run(atomix.getMembershipService().getLocalMember().id());

        System.out.println("init leadership: " + leadership);

```

And my clients are like this:
```
public class Client {

    private static Atomix getClient(int port) {
        AtomixBuilder builder = Atomix.builder();
        builder.withAddress("127.0.0.1", port)
                .withMembershipProvider(new BootstrapDiscoveryProvider(
                        Node.builder().withAddress("127.0.0.1:5001").build()))
                .addProfile(Profile.dataGrid());
        builder.withMembershipProvider(new BootstrapDiscoveryProvider(
                Node.builder().withAddress("127.0.0.1:5001").build()))
                .addProfile(Profile.client());
        Atomix atomix = builder.build();
        atomix.start().join();
        return atomix;
    }

    public static void main(String[] args) throws UnsupportedEncodingException {
        for (int i = 0; i < 5; ++i) {
            new T().start();
        }
    }

    private static class T extends Thread {

        private static int base = 6000;
        Atomix atomix;

        T() {
            atomix = getClient(base++);

        }

        @Override
        public void run() {
            for (int i = 0; i < 100; ++i) {
//                System.out.println("started");
                send();
            }
            atomix.stop().join();
        }

        private void send() {
            MemberId leader = atomix.<MemberId>leaderElectionBuilder("group").withSerializer(Serializer.using(Namespace.builder()
                    .register(Namespaces.BASIC)
                    .nextId(Namespaces.BEGIN_USER_CUSTOM_ID)
                    .register(MemberId.class)
                    .build())).build().getLeadership().leader().id();
            atomix.getMessagingService().sendAndReceive(
                    atomix.getMembershipService().getMember(leader).address(),
                    "test_type", "this is a msg to leader".getBytes())
                    .thenAccept(r -> System.out.println(new String(r)));
        }
    }
}

```
Server outputs:
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Atomix3Test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.5.0:exec (default-cli) @ Atomix3Test ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
trying to start server1 on port 5001.
ClusterMembershipEvent{type=MEMBER_ADDED, subject=Member{id=c3c7388c-ec6f-4596-92d9-f2221b807f91, address=127.0.0.1:5001, properties={}}, time=1532945157664}
server1 started on port 5001.
init leadership: Leadership{leader=Leader{id=c3c7388c-ec6f-4596-92d9-f2221b807f91, term=1, termStartTime=1532945158026}, candidates=[c3c7388c-ec6f-4596-92d9-f2221b807f91]}
ClusterMembershipEvent{type=MEMBER_ADDED, subject=Member{id=e4f8bb01-64f7-4b62-acdf-7477bdc19ee3, address=127.0.0.1:6000, properties={}}, time=1532945168835}
ClusterMembershipEvent{type=MEMBER_ADDED, subject=Member{id=729fa4c1-17c9-45a5-aed3-3c3bf07ad8bb, address=127.0.0.1:6001, properties={}}, time=1532945173605}
ClusterMembershipEvent{type=MEMBER_ADDED, subject=Member{id=c41d3bc2-86f6-46dd-9848-32d20919498f, address=127.0.0.1:6002, properties={}}, time=1532945174261}
ClusterMembershipEvent{type=REACHABILITY_CHANGED, subject=Member{id=e4f8bb01-64f7-4b62-acdf-7477bdc19ee3, address=127.0.0.1:6000, properties={}}, time=1532945356376}
ClusterMembershipEvent{type=REACHABILITY_CHANGED, subject=Member{id=c41d3bc2-86f6-46dd-9848-32d20919498f, address=127.0.0.1:6002, properties={}}, time=1532945356376}
ClusterMembershipEvent{type=REACHABILITY_CHANGED, subject=Member{id=729fa4c1-17c9-45a5-aed3-3c3bf07ad8bb, address=127.0.0.1:6001, properties={}}, time=1532945356476}
ClusterMembershipEvent{type=MEMBER_REMOVED, subject=Member{id=e4f8bb01-64f7-4b62-acdf-7477bdc19ee3, address=127.0.0.1:6000, properties={}}, time=1532945362957}
ClusterMembershipEvent{type=MEMBER_ADDED, subject=Member{id=10461a54-bd2a-4663-a620-cfe0bac04f79, address=127.0.0.1:6000, properties={}}, time=1532945362957}
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
ClusterMembershipEvent{type=MEMBER_REMOVED, subject=Member{id=729fa4c1-17c9-45a5-aed3-3c3bf07ad8bb, address=127.0.0.1:6001, properties={}}, time=1532945363916}
ClusterMembershipEvent{type=MEMBER_ADDED, subject=Member{id=81050b4c-fbd0-4a7d-8446-92fe412a4dc0, address=127.0.0.1:6001, properties={}}, time=1532945363916}
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6001, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6001, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6001, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6001, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6001, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6001, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
coming in test_type, addr:127.0.0.1:6000, cmd:this is a msg to leader
ClusterMembershipEvent{type=MEMBER_REMOVED, subject=Member{id=c41d3bc2-86f6-46dd-9848-32d20919498f, address=127.0.0.1:6002, properties={}}, time=1532945364700}
coming in test_type, addr:127.0.0.1:6001, cmd:this is a msg to leader
ClusterMembershipEvent{type=MEMBER_ADDED, subject=Member{id=a98723f3-966e-4e8c-8851-bd81491ded64, address=127.0.0.1:6002, properties={}}, time=1532945364700}
ClusterMembershipEvent{type=MEMBER_ADDED, subject=Member{id=295e6dff-235f-4166-a7fd-f4113a66b072, address=127.0.0.1:6003, properties={}}, time=1532945365162}
```

And the client outputs:
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Atomix3Test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.5.0:exec (default-cli) @ Atomix3Test ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
return_0_this is a msg to leader_from_server1
return_1_this is a msg to leader_from_server1
return_2_this is a msg to leader_from_server1
return_3_this is a msg to leader_from_server1
return_4_this is a msg to leader_from_server1
return_5_this is a msg to leader_from_server1
return_6_this is a msg to leader_from_server1
return_7_this is a msg to leader_from_server1
return_8_this is a msg to leader_from_server1
return_9_this is a msg to leader_from_server1
return_10_this is a msg to leader_from_server1
return_11_this is a msg to leader_from_server1
return_12_this is a msg to leader_from_server1
return_13_this is a msg to leader_from_server1
return_14_this is a msg to leader_from_server1
return_15_this is a msg to leader_from_server1
return_16_this is a msg to leader_from_server1
return_17_this is a msg to leader_from_server1
return_18_this is a msg to leader_from_server1
return_19_this is a msg to leader_from_server1
return_20_this is a msg to leader_from_server1
Exception in thread "Thread-0" java.lang.NullPointerException
	at cn.ac.iie.di.atomix3test.atomix.n.Client$T.send(Client.java:123)
	at cn.ac.iie.di.atomix3test.atomix.n.Client$T.run(Client.java:112)
Exception in thread "Thread-39" java.lang.NullPointerException
	at cn.ac.iie.di.atomix3test.atomix.n.Client$T.send(Client.java:123)
	at cn.ac.iie.di.atomix3test.atomix.n.Client$T.run(Client.java:112)
Exception in thread "Thread-103" java.lang.NullPointerException
	at cn.ac.iie.di.atomix3test.atomix.n.Client$T.send(Client.java:123)
	at cn.ac.iie.di.atomix3test.atomix.n.Client$T.run(Client.java:112)
Exception in thread "main" java.util.concurrent.CompletionException: io.atomix.primitive.PrimitiveException$Unavailable
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
	at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:911)
	at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:899)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at io.atomix.utils.concurrent.Futures.lambda$null$3(Futures.java:159)
	at io.atomix.utils.concurrent.ThreadPoolContext.lambda$new$0(ThreadPoolContext.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.atomix.primitive.PrimitiveException$Unavailable
	at io.atomix.protocols.backup.session.PrimaryBackupSessionClient.execute(PrimaryBackupSessionClient.java:177)
	at io.atomix.protocols.backup.session.PrimaryBackupSessionClient.lambda$null$6(PrimaryBackupSessionClient.java:215)
	... 8 more

```

**Environment**

 - Atomix: 3.0.0-rc5
 - OS:  windows 10 
 - JVM: 8u172
 - IDE: Netbeans 8.2

**Comment by kuujo** [comment]
There are a few problems here:

First is that all the nodes configured in this test have random identifiers. You must use `withId` each time you build a node to ensure you're building the same node. The identifier is the name by which node A contacts node B. Currently, the default for identifiers is to generate a UUID, which means each time `Node.builder().build()` is called you're getting what Atomix considers to be a different node. We used to default to IPs, but some nodes share an IP. Maybe we should use the IP:port as the default ID.

Second, the client is being configured with the `dataGrid()` profile, which means the "client" is actually attempting to participate in the data grid. So, when you start a new client, the partitions are being rebalanced and causing a loss of availability while the client is attempting to find the leader. Each node participates in the partition groups with which it's configured. If a node is configured with a primary-backup partition group - which the `dataGrid()` profile does - it will participate in primary-backup replication. You should use only the `client()` profile if you want a client.

Third, you're using an eventually consistent protocol to elect a leader, which is the source of the actual NPEs. I would _never_ recommend this. Leader election is not suited to eventual consistency. When the cluster is configured with the `dataGrid() profile or otherwise with a `PrimaryBackupPartitionGroup`, if no `RaftPartitionGroup` is available then an eventually consistent, hash-based primary election protocol is used. The group membership protocol is eventually consistent, so it's likely the client is seeing a different primary - which determines the leader - than the actual primary. This causes the client to query the wrong node, thus getting back a `null` leadership.

Finally, the client is building a new `LeaderElection` on each iteration, which is a pretty costly operation. Calling a primitive builder's `build()` method causes it to open a new logical session, register the session in a registry, and connect to one or many partitions before finally operating on the primitive. You should either use the primitive getters or build a single instance of the primitive per client to avoid creating too many sessions.

So, add a node ID to all the nodes and remove the `dataGrid()` profile from the client builders.

Also, this is really a help question and would have been great for the Google Group.
