### ISSUE TITLE
Maven Central badge not updating

### ISSUE THREAD

**Issue by kuujo** [atomix/atomix#767]
The Maven Central badge in the Atomix README still says `3.0.0-rc1`

**Comment by johnou** [comment]
Shows rc7 for me, can you right click it, copy link address and paste it here?

**Comment by johnou** [comment]
or better yet, try this

mkdir camo-purge && cd camo-purge && wget https://raw.githubusercontent.com/hobbyquaker/camo-purge/master/index.js && npm install --save-dev camo-purge && node index.js -r https://github.com/atomix/atomix

**Comment by johnou** [comment]
shouldn't be required in the future because of the fix we contributed https://github.com/softwaremill/maven-badges/pull/14

**Comment by kuujo** [comment]
https://maven-badges.herokuapp.com/maven-central/io.atomix/atomix

**Comment by johnou** [comment]
That's the link it points to, not the image url, better if you can run the set of commands above.

**Comment by kuujo** [comment]
You said the link address :-)

**Comment by kuujo** [comment]
https://camo.githubusercontent.com/79fc324bfeacb7d868595b942163a5dfc63de98b/68747470733a2f2f6d6176656e2d6261646765732e6865726f6b756170702e636f6d2f6d6176656e2d63656e7472616c2f696f2e61746f6d69782f61746f6d69782f62616467652e737667

**Comment by kuujo** [comment]
Buggy:
```
npm WARN saveError ENOENT: no such file or directory, open '/Users/jordanhalterman/Projects/atomix/camo-purge/camo-purge/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/jordanhalterman/Projects/atomix/camo-purge/camo-purge/package.json'
npm WARN camo-purge No description
npm WARN camo-purge No repository field.
npm WARN camo-purge No README data
npm WARN camo-purge No license field.

+ camo-purge@1.0.2
added 95 packages in 4.954s
module.js:491
    throw err;
    ^

Error: Cannot find module '/Users/jordanhalterman/Projects/atomix/camo-purge/camo-purge/index.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

**Comment by kuujo** [comment]
nvm got it to run

**Comment by johnou** [comment]
Now click https://camo.githubusercontent.com/79fc324bfeacb7d868595b942163a5dfc63de98b/68747470733a2f2f6d6176656e2d6261646765732e6865726f6b756170702e636f6d2f6d6176656e2d63656e7472616c2f696f2e61746f6d69782f61746f6d69782f62616467652e737667 and refresh a few times, should change.
