### ISSUE TITLE
Segment compacting throw exception when deleting file on Windows

### ISSUE THREAD

**Issue by yujiaxinlong** [atomix/atomix#779]
When running RaftPerformanceTest on Windows with default configuration(set DynamicCompaction to false to make sure it will compact).

I saw the issue #722 , and using the latest version. 

The platform is Windows7 Enterprise Edition 64bit, jdk1.8.0_181

it keeps reporting this exception:

```
java.lang.RuntimeException: java.nio.file.FileSystemException: target\perf-logs\1\atomix-1.log: The process cannot access the file because it is being used by another process.

	at io.atomix.storage.buffer.MappedBytes.delete(MappedBytes.java:135) ~[classes/:na]
	at io.atomix.storage.buffer.MappedBuffer.delete(MappedBuffer.java:197) ~[classes/:na]
	at io.atomix.storage.journal.JournalSegmentWriter.delete(JournalSegmentWriter.java:263) ~[classes/:na]
	at io.atomix.storage.journal.JournalSegment.delete(JournalSegment.java:190) ~[classes/:na]
	at io.atomix.storage.journal.SegmentedJournal.compact(SegmentedJournal.java:643) ~[classes/:na]
	at io.atomix.protocols.raft.storage.log.RaftLog.compact(RaftLog.java:128) ~[classes/:na]
	at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$compactLogs$7(RaftServiceManager.java:291) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```

when I change the data writing to file to a bigger string (like 1k bytes), it could compact normally at first, but still start to report this exception later.

`java.lang.RuntimeException: java.nio.file.FileSystemException: target\perf-logs\1\atomix-98.log: The process cannot access the file because it is being used by another process.`

I also tried this on Ubuntu, and in this case it didn't report this exception.

**Comment by yujiaxinlong** [comment]
@johnou 
sorry I changed some code when debug it.
updated exception stack with origin code.

I am sure I'm using the newest code,  it directly cloned from master branch,  the version number in pom.xml is <version>3.0.0-SNAPSHOT</version>, and I can see latest commits in gitlog

**Comment by johnou** [comment]
@yujiaxinlong would you kindly enable DEBUG logging for io.atomix.storage.buffer.MappedBytes , reproduce the bug and provide logs?

**Comment by yujiaxinlong** [comment]
@johnou 
sure, the debug logging is at below , but the log about BufferCleaner failed to free buffer seems didn't run.
And I tried this on Windows 10 and it will still report this exception directly.
I tried to trace the procedure of freeing buffer until the native method level, failed to find any problem. 

On thing might help is  that, as I mentioned it could run normally for a while when set the data to a bigger string, when I comment the  free buffer code in MappedBytes#close(), it will directly report exception at first.   
```
18:41:05.617 [raft-server-1] DEBUG i.a.storage.journal.SegmentedJournal - Created memory mapped segment: JournalSegment{id=5, version=1, index=37802, size=64}
18:41:05.621 [raft-server-3] DEBUG i.a.storage.journal.SegmentedJournal - Created memory mapped segment: JournalSegment{id=5, version=1, index=37802, size=64}
18:41:05.621 [raft-server-2] DEBUG i.a.storage.journal.SegmentedJournal - Created memory mapped segment: JournalSegment{id=5, version=1, index=37802, size=64}
18:41:05.718 [raft-server-1] DEBUG i.a.p.raft.impl.RaftServiceManager - RaftServer{1} - Compacting logs up to index 9485
18:41:05.719 [raft-server-1] DEBUG i.a.storage.journal.SegmentedJournal - atomix - Compacting 1 segment(s)
18:41:05.727 [raft-server-1] DEBUG io.atomix.utils.memory.BufferCleaner - java.nio.DirectByteBuffer.cleaner(): available
18:41:05.734 [raft-server-1] ERROR i.a.p.raft.impl.RaftServiceManager - RaftServer{1} - An exception occurred during log compaction: {}
java.lang.RuntimeException: java.nio.file.FileSystemException: target\perf-logs\1\atomix-1.log: 另一个程序正在使用此文件，进程无法访问。

	at io.atomix.storage.buffer.MappedBytes.delete(MappedBytes.java:135) ~[classes/:na]
	at io.atomix.storage.buffer.MappedBuffer.delete(MappedBuffer.java:197) ~[classes/:na]
	at io.atomix.storage.journal.JournalSegmentWriter.delete(JournalSegmentWriter.java:263) ~[classes/:na]
	at io.atomix.storage.journal.JournalSegment.delete(JournalSegment.java:190) ~[classes/:na]
	at io.atomix.storage.journal.SegmentedJournal.compact(SegmentedJournal.java:643) ~[classes/:na]
	at io.atomix.protocols.raft.storage.log.RaftLog.compact(RaftLog.java:128) ~[classes/:na]
	at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$compactLogs$7(RaftServiceManager.java:291) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.nio.file.FileSystemException: target\perf-logs\1\atomix-1.log: 另一个程序正在使用此文件，进程无法访问。

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86) ~[na:1.8.0_181]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[na:1.8.0_181]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[na:1.8.0_181]
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269) ~[na:1.8.0_181]
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103) ~[na:1.8.0_181]
	at java.nio.file.Files.delete(Files.java:1126) ~[na:1.8.0_181]
	at io.atomix.storage.buffer.MappedBytes.delete(MappedBytes.java:133) ~[classes/:na]
	... 13 common frames omitted
18:41:05.736 [raft-server-1] DEBUG i.a.p.raft.impl.RaftServiceManager - RaftServer{1} - Snapshotting services
18:41:05.736 [raft-server-1-state] DEBUG i.a.p.r.s.snapshot.SnapshotStore - Created memory snapshot: MemorySnapshot{index=37957}
18:41:05.737 [raft-server-1-state] DEBUG i.a.p.r.service.RaftServiceContext - PrimitiveService{2}{type=io.atomix.protocols.raft.test.RaftPerformanceTest$TestPrimitiveType@1d78fb2a, name=raft-performance-test} - Taking snapshot 37957
18:41:05.741 [raft-server-1-compaction] DEBUG i.a.p.r.s.snapshot.SnapshotStore - Created disk snapshot: FileSnapshot{index=37957}
```

**Comment by aruanruan** [comment]
@yujiaxinlong  
it is not a bug in windows, vm will release the native mapper file handler when global gc occures in minutes,  for my testing, after about 10+ logs file generated, the first log will be deleted successfully.

**Comment by yujiaxinlong** [comment]
@aruanruan 
Hi, are you also using windows? I tried to run the RaftPerformanceTest for around 20 minutes and generated 70+ logs and still keeps throwing this exception.
I slightly changed the code to

**Comment by aruanruan** [comment]
@yujiaxinlong window 10, are you using newest version?

**Comment by yujiaxinlong** [comment]
@aruanruan  Hi you are right, I tried again and this time it successfully deleted segment 1 to 30 when the 32nd segment created.  then stuck on segment 31 again.  

But it still a little bit strange to me that it should throw that much exceptions before run properly, since it run well on Linux.
