### ISSUE TITLE
multiple primitive groups will throw exception on getting primitives

### ISSUE THREAD

**Issue by linehrr** [atomix/atomix#839]
**Expected behavior**

when Atomix cluster is configured with multiple primitive groups, it should give option to choose which group user wants to create primitive on. 
same for getting the primitives, so user can specify not just the primitive name, but also the primitive group 

**Actual behavior**

when multiple primitive groups are configured, getting primitives by name will throw exception:
```
Exception in thread "main" io.atomix.utils.config.ConfigurationException: Primitive protocol is ambiguous: 2 partition groups found (data, raft)
	at io.atomix.primitive.PrimitiveBuilder.protocol(PrimitiveBuilder.java:125)
	at io.atomix.primitive.PrimitiveBuilder.newProxy(PrimitiveBuilder.java:163)
	at io.atomix.core.queue.impl.DefaultDistributedQueueBuilder.buildAsync(DefaultDistributedQueueBuilder.java:42)
	at io.atomix.core.impl.CorePrimitivesService.lambda$getPrimitiveAsync$0(CorePrimitivesService.java:341)
	at io.atomix.core.impl.CorePrimitiveCache.lambda$getPrimitive$0(CorePrimitiveCache.java:35)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.atomix.core.impl.CorePrimitiveCache.getPrimitive(CorePrimitiveCache.java:35)
	at io.atomix.core.impl.CorePrimitivesService.getPrimitiveAsync(CorePrimitivesService.java:336)
	at io.atomix.core.impl.CorePrimitivesService.getPrimitiveAsync(CorePrimitivesService.java:329)
	at io.atomix.primitive.PrimitiveFactory.getPrimitive(PrimitiveFactory.java:91)
	at io.atomix.core.impl.CorePrimitivesService.getQueue(CorePrimitivesService.java:237)
	at io.atomix.core.Atomix.getQueue(Atomix.java:594)
```

**Steps to reproduce**

1. setup Atomix cluster 
```java
    val atomix = Atomix.builder()
      .withMemberId(memberId)
      .withAddress(address)
      .withMembershipProvider(
        BootstrapDiscoveryProvider.builder()
          .withNodes(
            Node.builder()
              .withId("member-1")
              .withAddress("localhost:5671")
              .build(),
            Node.builder()
              .withId("member-2")
              .withAddress("localhost:5672")
              .build(),
            Node.builder()
              .withId("member-3")
              .withAddress("localhost:5673")
              .build()
          )
          .withFailureThreshold(2)
          .build()
      )
      .withManagementGroup(
        PrimaryBackupPartitionGroup.builder("system")
          .withNumPartitions(32)
          .build()
      )
      .withPartitionGroups(
        PrimaryBackupPartitionGroup.builder("data")   // first primitive group using PB partition
          .withNumPartitions(32)
          .build(),
        RaftPartitionGroup.builder("raft")                       // second primitive group using Raft partition
          .withDataDirectory(new File(s"/tmp/$memberId"))
          .withNumPartitions(6)
          .withMembers("member-1", "member-2", "member-3")
          .build()
      )
      .build()
```
2. create a queue with some specific protocol
```java
  val protocol = MultiPrimaryProtocol.builder()
    .withBackups(2)
    .withConsistency(Consistency.LINEARIZABLE)
    .withReplication(Replication.SYNCHRONOUS)
    .build()

  val queue = atomix.queueBuilder[String]("my-queue")
    .withProtocol(protocol)
    .build
```

3. get queue primitive from another node afterwards
```java
  val queue = atomix.
    getQueue[String]("my-queue")
```

**Environment**

 - Atomix: `3.0.5`
 - OS: `15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64`
 - JVM: `java version "1.8.0_162"`

**Comment by linehrr** [comment]
discard, protocol builder has an option, but it's just not very clear in the document. 
```java
  val protocol = MultiRaftProtocol.builder("raft")                // here you can specify the group name
    .withReadConsistency(ReadConsistency.LINEARIZABLE)
    .build()
```
