### ISSUE TITLE
Atomix starup fails when 3rd party typesafe configs are detected on classpath

### ISSUE THREAD

**Issue by imperatorx** [atomix/atomix#951]
**Actual behavior**

When a reference.conf or application.conf is present other than atomix (e.g. Caffeine's JCache config or Akka config), Atomix fails to start:

```
Caused by: io.atomix.utils.config.ConfigurationException: Unknown properties present in configuration: caffeine
	at io.atomix.core.utils.config.PolymorphicConfigMapper.checkRemainingProperties(PolymorphicConfigMapper.java:100) ~[atomix-3.0.8.jar:na]
	at io.atomix.utils.config.ConfigMapper.map(ConfigMapper.java:176) ~[atomix-utils-3.0.8.jar:na]
	at io.atomix.utils.config.ConfigMapper.map(ConfigMapper.java:134) ~[atomix-utils-3.0.8.jar:na]
	at io.atomix.utils.config.ConfigMapper.loadResources(ConfigMapper.java:124) ~[atomix-utils-3.0.8.jar:na]
	at io.atomix.utils.config.ConfigMapper.loadFiles(ConfigMapper.java:73) ~[atomix-utils-3.0.8.jar:na]
	at io.atomix.core.Atomix.config(Atomix.java:314) ~[atomix-3.0.8.jar:na]
	at io.atomix.core.Atomix.builder(Atomix.java:340) ~[atomix-3.0.8.jar:na]
	at io.atomix.core.Atomix.builder(Atomix.java:326) ~[atomix-3.0.8.jar:na]
```
It seems like Atomix is not ignoring 3rd party namespaces in the config.

Is there a way to disable atomix config file scanning, since I'm configuring atomix programmatically anyway?

 - Atomix: [e.g. 3.0.8]
 - OS: win64
 - JVM 11

**Comment by coutoPL** [comment]
Had same issue with akka. Dummy workaround was:
```
System.setProperty("akka", "")
System.setProperty("slick", "")
System.setProperty("sslConfig", "")
```
before atomix start.

**Comment by kuujo** [comment]
You can disable it by providing a custom `AtomixRegistry`, e.g. https://github.com/atomix/atomix/blob/master/core/src/main/java/io/atomix/core/registry/SimpleRegistry.java

The challenge is, then you have to ensure all the distributed primitives and other protocols are registered manually.

I think we should be able to disable the use of `application.conf` and `reference.conf` since they're not used and not expected by Atomix.

**Comment by coutoPL** [comment]
@kuujo oh, great. Good to know that. Will check it. Thanks for the hint

**Comment by kuujo** [comment]
I think you should be able to do this just by passing an empty `AtomixConfig` when creating the builder, e.g.:

```java
Atomix atomix = Atomix.builder(new AtomixConfig())
  ...
  .buid();
```

I think we should be able to disable classpath scanning for `reference.conf` and `application.conf`. Those are Typesafe Config specific files that Atomix neither expects nor wants.

**Comment by kuujo** [comment]
@coutoPL sorry ignore my first comment and use that one :-)

**Comment by coutoPL** [comment]
@kuujo I've just checked and indeed - the second solution with empty atomix config works fine! Thanks again.

**Comment by kuujo** [comment]
Awesome! We should leave this open and try to get rid of the usage of those files...

**Comment by amitvc** [comment]
@kuujo I want to start contributing to the project and learn more about it. Is this a good starter bug?

**Comment by sanderdg** [comment]
I had the same problem with Dagger but `Atomix atomix = Atomix.builder(new AtomixConfig())` works. Thanks @kuujo!
