### ISSUE TITLE
State machine operation failed when atomix restart

### ISSUE THREAD

**Issue by sndaergg** [atomix/atomix#972]
**I found excepiton in my atomix log:** 
00:15:03.026 [raft-server-raft-partition-1-state] ERROR i.a.p.raft.impl.RaftServiceManager - RaftServer{raft-partition-1} - Failed to take snapshot of service 284
java.lang.NullPointerException: null
        at io.atomix.core.value.impl.AbstractAtomicValueService.backup(AbstractAtomicValueService.java:55) ~[atomix-3.0.7.jar:na]
        at io.atomix.protocols.raft.service.RaftServiceContext.takeSnapshot(RaftServiceContext.java:293) ~[atomix-raft-3.0.7.jar:na]
        at io.atomix.protocols.raft.impl.RaftServiceManager.snapshotService(RaftServiceManager.java:483) [atomix-raft-3.0.7.jar:na]
        at io.atomix.protocols.raft.impl.RaftServiceManager.snapshot(RaftServiceManager.java:458) [atomix-raft-3.0.7.jar:na]
        at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$takeSnapshots$4(RaftServiceManager.java:237) [atomix-raft-3.0.7.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
00:15:05.526 [raft-server-raft-partition-1-state] ERROR i.a.p.raft.impl.RaftServiceManager - RaftServer{raft-partition-1} - Failed to take snapshot of service 284
java.lang.NullPointerException: null
        at io.atomix.core.value.impl.AbstractAtomicValueService.backup(AbstractAtomicValueService.java:55) ~[atomix-3.0.7.jar:na]
        at io.atomix.protocols.raft.service.RaftServiceContext.takeSnapshot(RaftServiceContext.java:293) ~[atomix-raft-3.0.7.jar:na]
        at io.atomix.protocols.raft.impl.RaftServiceManager.snapshotService(RaftServiceManager.java:483) [atomix-raft-3.0.7.jar:na]
        at io.atomix.protocols.raft.impl.RaftServiceManager.snapshot(RaftServiceManager.java:458) [atomix-raft-3.0.7.jar:na]
        at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$takeSnapshots$4(RaftServiceManager.java:237) [atomix-raft-3.0.7.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]

**An exception occurred while restarting Atomix:**
10:23:04.509 [raft-server-raft-partition-1-state] ERROR i.a.p.raft.impl.RaftServiceManager - RaftServer{raft-partition-1} - Failed to install snapshot for service group-failover-notif
java.nio.BufferUnderflowException: null
        at io.atomix.storage.buffer.AbstractBuffer.checkRead(AbstractBuffer.java:377) ~[atomix-storage-3.0.7.jar:na]
        at io.atomix.storage.buffer.AbstractBuffer.checkRead(AbstractBuffer.java:357) ~[atomix-storage-3.0.7.jar:na]
        at io.atomix.storage.buffer.AbstractBuffer.readInt(AbstractBuffer.java:564) ~[atomix-storage-3.0.7.jar:na]
        at io.atomix.protocols.raft.storage.snapshot.SnapshotReader.readInt(SnapshotReader.java:154) ~[atomix-raft-3.0.7.jar:na]
        at io.atomix.primitive.service.impl.DefaultBackupInput.readInt(DefaultBackupInput.java:131) ~[atomix-primitive-3.0.7.jar:na]
        at io.atomix.core.value.impl.AbstractAtomicValueService.restore(AbstractAtomicValueService.java:61) ~[atomix-3.0.7.jar:na]
        at io.atomix.protocols.raft.service.RaftServiceContext.installSnapshot(RaftServiceContext.java:267) ~[atomix-raft-3.0.7.jar:na]
        at io.atomix.protocols.raft.impl.RaftServiceManager.installService(RaftServiceManager.java:529) [atomix-raft-3.0.7.jar:na]
        at io.atomix.protocols.raft.impl.RaftServiceManager.install(RaftServiceManager.java:502) [atomix-raft-3.0.7.jar:na]
        at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$apply$12(RaftServiceManager.java:419) [atomix-raft-3.0.7.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
10:23:04.607 [raft-server-raft-partition-2] WARN  i.a.p.raft.roles.LeaderAppender - RaftServer{raft-partition-2} - Failed to configure uranus-atomix-3

**What causes this problem?**
Onos version: 1.14.1
atomix version 3.0.7
atomix config:
cluster {
  cluster-id: uranus-atomix-cluster
  discovery {
    type: bootstrap
    nodes.1 {
      id: uranus-atomix-1
      address: "127.0.0.1:5901"
    }
    nodes.2 {
      id: uranus-atomix-2
      address: "127.0.0.1:5902"
    }
    nodes.3 {
      id: uranus-atomix-3
      address: "127.0.0.1:5903"
    }
  }
}

management-group {
  type: raft
  partitions: 1
  storage.level: disk
  members: [uranus-atomix-1, uranus-atomix-2, uranus-atomix-3]
}

partition-groups.raft {
  type: raft
  partitions: 3
  storage.level: disk
  members: [uranus-atomix-1, uranus-atomix-2, uranus-atomix-3]
}

**Comment by kuujo** [comment]
I think this is a bug that’s fixed in 3.1 #959

We need to backport that fix.

**Comment by kuujo** [comment]
Sorry #952 and #959

**Comment by kuujo** [comment]
If you need a stable release, this should be fixed in the latest 3.1.4 release. If you’d like to backport the two changes that would be great. I’m traveling so won’t get to it until this weekend.

**Comment by sndaergg** [comment]
Thanks for your reply!
I have found the fixed code in 3.1, but I'm using onos 1.14.1，corresponding atomix version 3.0.7 .
Can I only upgrade atomix to 3.1.4?
![image](https://user-images.githubusercontent.com/16028278/51017345-c085d580-15ae-11e9-8d54-6a185f4e930a.png)

**Comment by sndaergg** [comment]
Can you fix this two bugs in 3.0.x，We have used ONOS 1.14 in the production environment.
Thank you for your kindness！！！

**Comment by sndaergg** [comment]
**After I back port #952 and #959 in Atomix 3.0.x and run 12 hours，another excetpion arised while restart my onos and atomix cluster: **
10:02:56.624 [raft-server-raft-partition-2-state] WARN  i.a.p.s.impl.DefaultServiceExecutor - PrimitiveService{56}{type=AtomicValueType{name=atomic-value}, name=onos-apps-activation-topic} - State machine operation failed: java.lang.reflect.InvocationTargetException
10:02:56.627 [raft-server-raft-partition-2-state] WARN  i.a.p.s.impl.DefaultServiceExecutor - PrimitiveService{56}{type=AtomicValueType{name=atomic-value}, name=onos-apps-activation-topic} - State machine operation failed: java.lang.reflect.InvocationTargetException
10:02:56.647 [raft-server-raft-partition-2] WARN  i.a.protocols.raft.roles.LeaderRole - RaftServer{raft-partition-2}{role=LEADER} - An application error occurred: {}
io.atomix.primitive.PrimitiveException$ServiceException: java.lang.reflect.InvocationTargetException
        at io.atomix.primitive.service.AbstractPrimitiveService.lambda$configure$2(AbstractPrimitiveService.java:151) ~[atomix-primitive-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.primitive.service.impl.DefaultServiceExecutor.lambda$register$1(DefaultServiceExecutor.java:154) ~[atomix-primitive-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.primitive.service.impl.DefaultServiceExecutor.apply(DefaultServiceExecutor.java:182) ~[atomix-primitive-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.primitive.service.AbstractPrimitiveService.apply(AbstractPrimitiveService.java:113) ~[atomix-primitive-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.protocols.raft.service.RaftServiceContext.applyCommand(RaftServiceContext.java:520) ~[atomix-raft-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.protocols.raft.service.RaftServiceContext.executeCommand(RaftServiceContext.java:492) ~[atomix-raft-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.protocols.raft.impl.RaftServiceManager.applyCommand(RaftServiceManager.java:807) ~[atomix-raft-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$apply$12(RaftServiceManager.java:424) ~[atomix-raft-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.0.9-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_171]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
        at io.atomix.primitive.service.AbstractPrimitiveService.lambda$configure$2(AbstractPrimitiveService.java:149) ~[atomix-primitive-3.0.9-SNAPSHOT.jar:na]
        ... 15 common frames omitted
Caused by: java.lang.IllegalStateException: session is expired
        at com.google.common.base.Preconditions.checkState(Preconditions.java:456) ~[guava-22.0.jar:na]
        at io.atomix.protocols.raft.session.RaftSession.publish(RaftSession.java:438) ~[atomix-raft-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.primitive.session.impl.AbstractSession.publish(AbstractSession.java:101) ~[atomix-primitive-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.primitive.session.impl.ClientSession$SessionProxyHandler.invoke(ClientSession.java:127) ~[atomix-primitive-3.0.9-SNAPSHOT.jar:na]
        at com.sun.proxy.$Proxy9.change(Unknown Source) ~[na:na]
        at io.atomix.core.value.impl.AbstractAtomicValueService.lambda$null$0(AbstractAtomicValueService.java:75) ~[atomix-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.primitive.session.impl.ClientSession$SessionProxy.accept(ClientSession.java:107) ~[atomix-primitive-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.primitive.session.impl.ClientSession.accept(ClientSession.java:84) ~[atomix-primitive-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.core.value.impl.AbstractAtomicValueService.lambda$updateAndNotify$1(AbstractAtomicValueService.java:75) ~[atomix-3.0.9-SNAPSHOT.jar:na]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_171]
        at io.atomix.core.value.impl.AbstractAtomicValueService.updateAndNotify(AbstractAtomicValueService.java:75) ~[atomix-3.0.9-SNAPSHOT.jar:na]
        at io.atomix.core.value.impl.AbstractAtomicValueService.set(AbstractAtomicValueService.java:82) ~[atomix-3.0.9-SNAPSHOT.jar:na]
        ... 20 common frames omitted
10:02:56.653 [raft-server-raft-partition-2-state] WARN  i.a.p.s.impl.DefaultServiceExecutor - PrimitiveService{56}{type=AtomicValueType{name=atomic-value}, name=onos-apps-activation-topic} - State machine operation failed: java.lang.reflect.InvocationTargetException

Should expired sessions not enter this process?expect your reply!
